const profileTypes = {
  GET_PROFILE: "GET_PROFILE",
  GET_PROFILES: "GET_PROFILES",
  PROFILE_LOADING: "PROFILE_LOADING",
  CLEAR_CURRENT_PROFILE: "CLEAR_CURRENT_PROFILE",
  CREATE_PROFILE: "CREATE_PROFILE",
};

export default profileTypes;
