const errorTypes = {
  SIGN_UP_FAILURE: "SIGN_UP_FAILURE",
  SIGN_IN_FAILURE: "SIGN_IN_FAILURE",
  GET_PROFILE_FAILURE: "GET_PROFILE_FAILURE",
  GET_PROFILES_FAILURE: "GET_PROFILES_FAILURE",
  CREATE_PROFILE_FAILURE: "CREATE_PROFILE_FAILURE",
  DELETE_PROFILE_FAILURE: "DELETE_PROFILE_FAILURE",
  ADD_EXPERIENCE_FAILURE: "ADD_EXPERIENCE_FAILURE",
  ADD_EDUCATION_FAILURE: "ADD_EDUCATION_FAILURE",
  DELETE_EDUCATION_FAILURE: "DELETE_EDUCATION_FAILURE",
  DELETE_EXPERIENCE_FAILURE: "DELETE_EXPERIENCE_FAILURE",
};

export default errorTypes;
