const errorTypes = {
  SIGN_UP_FAILURE: "SIGN_UP_FAILURE",
  SIGN_IN_FAILURE: "SIGN_IN_FAILURE",
  GET_PROFILE_FAILURE: "GET_PROFILE_FAILURE",
  GET_PROFILES_FAILURE: "GET_PROFILES_FAILURE",
  CREATE_PROFILE_FAILURE: "CREATE_PROFILE_FAILURE",
  DELETE_PROFILE_FAILURE: "DELETE_PROFILE_FAILURE",
  ADD_EXPERIENCE_FAILURE: "ADD_EXPERIENCE_FAILURE",
  ADD_EDUCATION_FAILURE: "ADD_EDUCATION_FAILURE",
  DELETE_EDUCATION_FAILURE: "DELETE_EDUCATION_FAILURE",
  DELETE_EXPERIENCE_FAILURE: "DELETE_EXPERIENCE_FAILURE",
  ADD_POST_FAILURE: "ADD_POST_FAILURE",
  GET_POSTS_FAILURE: "GET_POSTS_FAILURE",
  DELETE_POST_FAILURE: "DELETE_POST_FAILURE",
  ADD_LIKE_FAILURE: "ADD_LIKE_FAILURE",
  REMOVE_LIKE_FAILURE: "REMOVE_LIKE_FAILURE",
  ADD_COMMENT_FAILURE: "ADD_COMMENT_FAILURE",
  DELETE_COMMENT_FAILURE: "DELETE_COMMENT_FAILURE",
  CLEAR_ERROR_MESSAGE: "CLEAR_ERROR_MESSAGE",
};

export default errorTypes;
